export const IS_LOADING_AUTH = "IS_LOADING_AUTH";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";

export const IS_LOADING = "IS_LOADING";
export const IS_LOADING_CLIENTS = "IS_LOADING_CLIENTS";
export const FETCH_CLIENTS_NAME = "FETCH_CLIENTS_NAME";
export const ACTIVE_FORMS = "ACTIVE_FORMS";
export const SET_ALL_FORMS = "SET_ALL_FORMS";
export const FETCH_CATEGORY_BY_FORM = "FETCH_CATEGORY_BY_FORM";
export const SET_QAS_NAME = "SET_QAS_NAME";
export const SET_AGENT_NAME = "SET_AGENT_NAME";
export const SET_TEAMLEAD_NAME = "SET_TEAMLEAD_NAME";

export const IS_LOADING_QAS = "IS_LOADING_QAS";
export const IS_ADDING_QUESTION = "IS_ADDING_QUESTION";
export const IS_DELETING = "IS_DELETING";
export const SET_FORMS_NAMES_FILTER = "SET_FORMS_NAMES_FILTER";
export const GET_ALL_FORMS_TICKETS = "GET_ALL_FORMS_TICKETS";
export const SELECTED_FORM_TO_EVALUATE = "SELECTED_FORM_TO_EVALUATE";
export const GET_GRADED_JSON_WITH_TAGS = "GET_GRADED_JSON_WITH_TAGS";
export const IS_SUBMITTING_TICKET = "IS_SUBMITTING_TICKET";

// attendance types
export const FETCH_ATTENDANCE_MANAGEMENT = "FETCH_ATTENDANCE_MANAGEMENT";
export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const FETCH_TEAM_LEAD = "FETCH_TEAM_LEAD";
export const FETCH_DEPARTMENT_DIRECTOR = "FETCH_DEPARTMENT_DIRECTOR";
export const FETCH_DEPARTMENT_MANAGER = "FETCH_DEPARTMENT_MANAGER";
export const FETCH_AOM = "FETCH_AOM";
export const FETCH_SOM = "FETCH_SOM";
export const FETCH_CLIENT_NAME_TMF = "FETCH_CLIENT_NAME_TMF";
export const FETCH_MEMBER_FILTER_DATA = "FETCH_MEMBER_FILTER_DATA";

export const FETCH_OPSTL_FILTER_DATA = "FETCH_OPSTL_FILTER_DATA";
export const FETCH_OM_FILTER_DATA = "FETCH_OM_FILTER_DATA";
export const FETCH_AOM_FILTER_DATA = "FETCH_AOM_FILTER_DATA";
export const FETCH_CLIENTS_FILTER_DATA = "FETCH_CLIENTS_FILTER_DATA";
export const FETCH_TEAM_FILTER_DATA = "FETCH_TEAM_FILTER_DATA";
export const FETCH_CSM_DATA = "FETCH_CSM_DATA";
export const FETCH_AGENT_DATA = "FETCH_AGENT_DATA";
export const FETCH_OM_DATA = "FETCH_OM_DATA";
