export const ATT_REASONS = [
  "Approved Extended Lunch",
  "Bereavement Leave",
  "Client Changed Schedule - New Schedule",
  "Client Changed Schedule - Temporary",
  "Client Device Issue",
  "Client on Holiday",
  "Currently Onboarding - New Client",
  "Flexible Schedule",
  "Floating Schedule",
  "Hours not met - Completed Shift",
  "Hubstaff Issue",
  "Hubstaff Issue: Incorrect Weekly Hours",
  "Hubstaff Issue: Locked Timesheet",
  "Hubstaff Issue: Stopped Working",
  "Hubstaff Issue: Software Update",
  "Idle Time: Low Ticket Volume",
  "Idle Time: Minimal",
  "Incorrect Minimum Hours Plotted",
  "LOA",
  "Offboarded",
  "Outdated HS Schedule",
  "PTO",
  "Resigned",
  "VTO",
  "Paternity Leave",
  "Maternity Leave",
  "Minimal: Agent Device Update",
  "Health Issue/Sick Leave - HR Validated",
  "Exempted",
  "Power & ISP Interruption",
  "Agent Device Issue",
  "Emergency",
  "Forgot to turn on Hubstaff",
  "Health Issue/Sick Leave",
  "Idle Time: Excessive",
  "ISP Interruption",
  "NCNS",
  "No Reason Provided",
  "Overlunch/Overbreak",
  "Pending Agent Confirmation",
  "Personal Reasons",
  "Unresponded",
  "Power Interruption",
  "Woke Up Late",
  "Others",
  "Agent in live training",
  "On Time", // not        valid
  "No Schedule", // not    valid
  "Rest Day", // not       valid
];

export const ATT_REASONS_STATUS = [
  { reason: "Approved Extended Lunch", validity: "VALID" },
  { reason: "Bereavement Leave", validity: "VALID" },
  { reason: "Client Changed Schedule - New Schedule", validity: "VALID" },
  { reason: "Client Changed Schedule - Temporary", validity: "VALID" },
  { reason: "Client Device Issue", validity: "VALID" },
  { reason: "Client on Holiday", validity: "VALID" },
  { reason: "Currently Onboarding - New Client", validity: "VALID" },
  { reason: "Flexible Schedule", validity: "VALID" },
  { reason: "Floating Schedule", validity: "VALID" },
  { reason: "Hours not met - Completed Shift", validity: "VALID" },
  { reason: "Hubstaff Issue", validity: "VALID" },
  { reason: "Hubstaff Issue: Incorrect Weekly Hours", validity: "VALID" },
  { reason: "Hubstaff Issue: Locked Timesheet", validity: "VALID" },
  { reason: "Hubstaff Issue: Stopped Working", validity: "VALID" },
  { reason: "Hubstaff Issue: Software Update", validity: "VALID" },
  { reason: "Idle Time: Low Ticket Volume", validity: "VALID" },
  { reason: "Idle Time: Minimal", validity: "VALID" },
  { reason: "Incorrect Minimum Hours Plotted", validity: "VALID" },
  { reason: "LOA", validity: "VALID" },
  { reason: "Offboarded", validity: "VALID" },
  { reason: "Outdated HS Schedule", validity: "VALID" },
  { reason: "PTO", validity: "VALID" },
  { reason: "Resigned", validity: "VALID" },
  { reason: "VTO", validity: "VALID" },
  { reason: "Paternity Leave", validity: "VALID" },
  {
    reason: "Maternity Leave",
    validity: "VALID",
    description:
      "Absence approved due to pregnancy, childbirth, or postnatal recovery, in accordance with company policy and local labor laws.",
  },
  { reason: "Minimal: Agent Device Update", validity: "VALID" },
  { reason: "Health Issue/Sick Leave - HR Validated", validity: "VALID" },
  { reason: "Exempted", validity: "VALID" },
  { reason: "Agent in live training", validity: "VALID" },
  { reason: "Unpaid Time Off", validity: "VALID" },
  { reason: "Schedule plotted for Billing Purposes", validity: "VALID" },
  { reason: "Power & ISP Interruption", validity: "INVALID" },
  { reason: "Agent Device Issue", validity: "INVALID" },
  { reason: "Emergency", validity: "INVALID" },
  { reason: "Forgot to turn on Hubstaff", validity: "INVALID" },
  { reason: "Health Issue/Sick Leave", validity: "INVALID" },
  { reason: "Idle Time: Excessive", validity: "INVALID" },
  { reason: "ISP Interruption", validity: "INVALID" },
  { reason: "NCNS", validity: "INVALID" },
  { reason: "No Reason Provided", validity: "INVALID" },
  { reason: "Overlunch/Overbreak", validity: "INVALID" },
  { reason: "Pending Agent Confirmation", validity: "INVALID" },
  { reason: "Personal Reasons", validity: "INVALID" },
  { reason: "Unresponded", validity: "INVALID" },
  { reason: "Power Interruption", validity: "INVALID" },
  { reason: "Woke Up Late", validity: "INVALID" },
  { reason: "On Time", validity: "VALID" },
  { reason: "No Schedule", validity: "VALID" },
  { reason: "Rest Day", validity: "VALID" },
  { reason: "Calamity/Force of Nature", validity: "VALID" },
  { reason: "Others", validity: "INVALID" },
];
export const handleReasonRules = (reasonValue) => {
  return (
    reasonValue == "Flexible Schedule" ||
    // reasonValue == "PTO" ||
    reasonValue == "LOA" ||
    reasonValue == "Maternity Leave" ||
    reasonValue == "Paternity Leave" ||
    reasonValue == "Schedule plotted for Billing Purposes"
  );
};
